// Mock data for trips
export const mockTrips = [
  // Inter-city trips (35-seater) - All starting from Đà Nẵng
  {
    id: 1,
    from: 'Đà Nẵng',
    to: 'Hà Nội',
    date: '2024-01-15',
    category: 'interCity',
    departureTime: '05:00',
    arrivalTime: '15:30',
    duration: '9h 30m',
    busType: 'bus',
    seatsAvailable: 25,
    totalSeats: 35,
    seats: 35,
    price: 250000,
    operator: 'BusGo',
    amenities: ['AC', 'Wifi', 'Phone Charger'],
    rating: 4.5,
    occupiedSeats: [1, 3, 5, 10, 15, 20, 25]
  },
  {
    id: 2,
    from: 'Đà Nẵng',
    to: 'Hà Nội',
    date: '2024-01-15',
    category: 'interCity',
    departureTime: '07:30',
    arrivalTime: '17:00',
    duration: '9h 30m',
    busType: 'minibus',
    seatsAvailable: 8,
    totalSeats: 35,
    seats: 35,
    price: 450000,
    operator: 'BusGo',
    amenities: ['AC', 'Wifi', 'Phone Charger', 'Blanket'],
    rating: 4.8,
    occupiedSeats: [2, 4, 6, 8]
  },
  {
    id: 3,
    from: 'Đà Nẵng',
    to: 'Hà Nội',
    date: '2024-01-15',
    category: 'interCity',
    departureTime: '09:00',
    arrivalTime: '18:30',
    duration: '9h 30m',
    busType: 'bus',
    seatsAvailable: 15,
    totalSeats: 35,
    seats: 35,
    price: 280000,
    operator: 'BusGo',
    amenities: ['AC', 'Wifi', 'Phone Charger', 'Toilet'],
    rating: 4.6,
    occupiedSeats: [1, 5, 10, 15, 20]
  },
  {
    id: 4,
    from: 'Đà Nẵng',
    to: 'Hà Nội',
    date: '2024-01-15',
    category: 'interCity',
    departureTime: '10:30',
    arrivalTime: '20:00',
    duration: '9h 30m',
    busType: 'minibus',
    seatsAvailable: 12,
    totalSeats: 35,
    seats: 35,
    price: 480000,
    operator: 'BusGo',
    amenities: ['AC', 'Wifi', 'Phone Charger', 'Blanket'],
    rating: 4.7,
    occupiedSeats: [3, 7, 11]
  },
  {
    id: 5,
    from: 'Đà Nẵng',
    to: 'Sài Gòn',
    date: '2024-01-15',
    category: 'interCity',
    departureTime: '14:00',
    arrivalTime: '23:30',
    duration: '9h 30m',
    busType: 'bus',
    seatsAvailable: 8,
    totalSeats: 35,
    seats: 35,
    price: 200000,
    operator: 'BusGo',
    amenities: ['AC'],
    rating: 4.0,
    occupiedSeats: [2, 6, 10, 14, 18, 22, 26, 30]
  },
  {
    id: 6,
    from: 'Đà Nẵng',
    to: 'Sài Gòn',
    date: '2024-01-15',
    category: 'interCity',
    departureTime: '16:30',
    arrivalTime: '02:00',
    duration: '9h 30m',
    busType: 'bus',
    seatsAvailable: 32,
    totalSeats: 35,
    seats: 35,
    price: 220000,
    operator: 'BusGo',
    amenities: ['AC', 'Blanket'],
    rating: 4.4,
    occupiedSeats: [1, 2, 3]
  },
  {
    id: 7,
    from: 'Đà Nẵng',
    to: 'Sài Gòn',
    date: '2024-01-15',
    category: 'interCity',
    departureTime: '18:00',
    arrivalTime: '03:30',
    duration: '9h 30m',
    busType: 'bus',
    seatsAvailable: 38,
    totalSeats: 35,
    seats: 35,
    price: 180000,
    operator: 'BusGo',
    amenities: ['AC', 'Pillow & Blanket', 'Toilet'],
    rating: 4.3,
    occupiedSeats: []
  },
  {
    id: 8,
    from: 'Đà Nẵng',
    to: 'Sài Gòn',
    date: '2024-01-15',
    category: 'interCity',
    departureTime: '20:00',
    arrivalTime: '05:30',
    duration: '9h 30m',
    busType: 'minibus',
    seatsAvailable: 5,
    totalSeats: 35,
    seats: 35,
    price: 520000,
    operator: 'BusGo',
    amenities: ['AC', 'Wifi', 'Phone Charger', 'Blanket', 'Toilet'],
    rating: 4.9,
    occupiedSeats: [5, 10, 15, 20, 25, 30]
  },
  {
    id: 9,
    from: 'Đà Nẵng',
    to: 'Huế',
    date: '2024-01-15',
    category: 'interCity',
    departureTime: '22:00',
    arrivalTime: '07:30',
    duration: '9h 30m',
    busType: 'bus',
    seatsAvailable: 35,
    totalSeats: 35,
    seats: 35,
    price: 190000,
    operator: 'BusGo',
    amenities: ['AC', 'Pillow & Blanket'],
    rating: 4.2,
    occupiedSeats: []
  },
  {
    id: 10,
    from: 'Đà Nẵng',
    to: 'Quảng Nam',
    date: '2024-01-15',
    category: 'interCity',
    departureTime: '23:30',
    arrivalTime: '09:00',
    duration: '9h 30m',
    busType: 'bus',
    seatsAvailable: 42,
    totalSeats: 35,
    seats: 35,
    price: 170000,
    operator: 'BusGo',
    amenities: ['AC'],
    rating: 4.1,
    occupiedSeats: [1, 2]
  },
  // City transit trips (16-seater)
  {
    id: 11,
    from: 'Bến xe trung tâm',
    to: 'Sân bay Quốc tế Đà Nẵng',
    date: '2024-01-15',
    category: 'city',
    departureTime: '06:00',
    arrivalTime: '06:30',
    duration: '30m',
    busType: 'minibus',
    seatsAvailable: 12,
    totalSeats: 16,
    seats: 16,
    price: 50000,
    operator: 'BusGo',
    amenities: ['AC'],
    rating: 4.3,
    occupiedSeats: [1, 5, 10]
  },
  {
    id: 12,
    from: 'Bến xe trung tâm',
    to: 'Bãi biển Mỹ Khê',
    date: '2024-01-15',
    category: 'city',
    departureTime: '07:00',
    arrivalTime: '07:20',
    duration: '20m',
    busType: 'minibus',
    seatsAvailable: 14,
    totalSeats: 16,
    seats: 16,
    price: 35000,
    operator: 'BusGo',
    amenities: ['AC'],
    rating: 4.4,
    occupiedSeats: [3, 8]
  },
  {
    id: 13,
    from: 'Cầu Rồng',
    to: 'Phố cổ Hội An',
    date: '2024-01-15',
    category: 'city',
    departureTime: '08:00',
    arrivalTime: '08:45',
    duration: '45m',
    busType: 'minibus',
    seatsAvailable: 10,
    totalSeats: 16,
    seats: 16,
    price: 60000,
    operator: 'BusGo',
    amenities: ['AC', 'Wifi'],
    rating: 4.5,
    occupiedSeats: [2, 4, 6, 8, 10, 12]
  },
  {
    id: 14,
    from: 'Sân bay Quốc tế Đà Nẵng',
    to: 'Bãi biển Non Nước',
    date: '2024-01-15',
    category: 'city',
    departureTime: '09:00',
    arrivalTime: '09:50',
    duration: '50m',
    busType: 'minibus',
    seatsAvailable: 13,
    totalSeats: 16,
    seats: 16,
    price: 55000,
    operator: 'BusGo',
    amenities: ['AC'],
    rating: 4.2,
    occupiedSeats: [1, 7, 14]
  },
  {
    id: 15,
    from: 'Đại học Duy Tân',
    to: 'Trung tâm thành phố',
    date: '2024-01-15',
    category: 'city',
    departureTime: '10:00',
    arrivalTime: '10:25',
    duration: '25m',
    busType: 'minibus',
    seatsAvailable: 15,
    totalSeats: 16,
    seats: 16,
    price: 40000,
    operator: 'BusGo',
    amenities: ['AC'],
    rating: 4.6,
    occupiedSeats: [5]
  },
  {
    id: 16,
    from: 'Khu công nghiệp Hòa Cầm',
    to: 'Bến xe trung tâm',
    date: '2024-01-15',
    category: 'city',
    departureTime: '11:00',
    arrivalTime: '11:35',
    duration: '35m',
    busType: 'minibus',
    seatsAvailable: 11,
    totalSeats: 16,
    seats: 16,
    price: 45000,
    operator: 'BusGo',
    amenities: ['AC'],
    rating: 4.1,
    occupiedSeats: [2, 6, 9, 12, 15]
  },
  {
    id: 17,
    from: 'Đại học Kinh tế Đà Nẵng',
    to: 'Cộng Hòa (trung tâm)',
    date: '2024-01-15',
    category: 'city',
    departureTime: '12:00',
    arrivalTime: '12:20',
    duration: '20m',
    busType: 'minibus',
    seatsAvailable: 16,
    totalSeats: 16,
    seats: 16,
    price: 38000,
    operator: 'BusGo',
    amenities: ['AC'],
    rating: 4.7,
    occupiedSeats: []
  },
  {
    id: 18,
    from: 'Hùng Vương',
    to: 'Phạm Văn Đồng',
    date: '2024-01-15',
    category: 'city',
    departureTime: '13:00',
    arrivalTime: '13:15',
    duration: '15m',
    busType: 'minibus',
    seatsAvailable: 14,
    totalSeats: 16,
    seats: 16,
    price: 32000,
    operator: 'BusGo',
    amenities: ['AC'],
    rating: 4.4,
    occupiedSeats: [4, 11]
  }
]

// Mock payment methods
export const mockPaymentMethods = {
  visa: {
    name: 'Visa',
    category: 'Thẻ quốc tế',
    logo: '💳',
    description: 'Thanh toán qua thẻ Visa quốc tế'
  },
  mastercard: {
    name: 'Mastercard',
    category: 'Thẻ quốc tế',
    logo: '💳',
    description: 'Thanh toán qua thẻ Mastercard quốc tế'
  },
  jcb: {
    name: 'JCB',
    category: 'Thẻ quốc tế',
    logo: '💳',
    description: 'Thanh toán qua thẻ JCB quốc tế'
  },
  atm_napas: {
    name: 'ATM Napas',
    category: 'Thẻ nội địa',
    logo: '🏦',
    description: 'Thanh toán qua thẻ ATM nội địa qua cổng Napas'
  },
  momo: {
    name: 'Momo',
    category: 'Ví điện tử',
    logo: '📱',
    description: 'Thanh toán qua ví điện tử Momo'
  },
  zalopay: {
    name: 'ZaloPay',
    category: 'Ví điện tử',
    logo: '📱',
    description: 'Thanh toán qua ví điện tử ZaloPay'
  },
  vnpay: {
    name: 'VNPay',
    category: 'Ví điện tử',
    logo: '📱',
    description: 'Thanh toán qua ví điện tử VNPay'
  }
}

// Cargo types configuration
export const cargoTypes = {
  none: {
    label: 'Không gửi hàng',
    priceRange: 'Miễn phí',
    minPrice: 0,
    maxPrice: 0
  },
  light: {
    label: 'Hàng nhẹ/Tài liệu (<10kg)',
    priceRange: 'Miễn phí',
    minPrice: 0,
    maxPrice: 0
  },
  heavy: {
    label: 'Hàng nặng (>10kg)',
    priceRange: '3.000đ - 6.500đ/kg',
    minPrice: 3000,
    maxPrice: 6500
  },
  scooter: {
    label: 'Xe tay ga',
    priceRange: '1.000.000đ',
    minPrice: 1000000,
    maxPrice: 1000000
  },
  maxi_scooter: {
    label: 'Xe tay côn/SH',
    priceRange: '1.300.000đ',
    minPrice: 1300000,
    maxPrice: 1300000
  },
  motorcycle: {
    label: 'Gửi xe máy thông thường',
    priceRange: '320.000đ - 400.000đ',
    minPrice: 320000,
    maxPrice: 400000
  }
}
